[package]
name = "bamboo-shoots"
version = "0.1.0"
authors = ["bill.huang <bill.huang@mplusmedia.cn>"]
edition = "2021"

[dependencies]
regex = "1.3"
tokio = {version = "0.2", features = ["rt-core", "rt-threaded"]}
rand = "0.8"